### ISSUE TITLE
Error when requiring fibrous more than once

### ISSUE THREAD

**Issue by willshulman** [goodeggs/fibrous#31]
If you require fibrous from more than one module in different packages you get the following error. In my case I have:
- Package A depends on Package B and Package C
- Package B depends on fibrous
- Package C depends on fibrous

I am using version 0.3.3

```
node_modules/fibrous/lib/fibrous.js:107
    return Object.defineProperty(target, propertyName, {
                  ^
TypeError: Cannot redefine property: future
    at Function.defineProperty (native)
    at defineMemoizedPerInstanceProperty (/Users/will/src/github/objectlabs/leafnode/node_modules/fibrous/lib/fibrous.js:107:19)
    at Object.<anonymous> (/Users/will/src/github/objectlabs/leafnode/node_modules/fibrous/lib/fibrous.js:135:5)
    at Object.<anonymous> (/Users/will/src/github/objectlabs/leafnode/node_modules/fibrous/lib/fibrous.js:189:4)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)

```

**Comment by ide** [comment]
node-fibers 1.0.4 includes a guard against double-inclusion, so it'd be safe if fibrous were to do the same.  Probably the simplest way is to expose a global reference to fibrous, something like:

```
# fibrous.coffee
if process.fibrous?
  module.exports = process.fibrous
  return
...
process.fibrous = fibrous
```

**Comment by willshulman** [comment]
I don't believe this is a problem with double including node-fibers. The problem is the fact that Object.defineProperty is called twice on the same target, which is done as part of the fibrous module initialization. It would seem onerous for every client to need to do something like you suggested. Might it not be better for the fibrous library to check if it has already defined the property on the target?

**Comment by ide** [comment]
Yeah I agree. I meant that before the node-fibers fix you could have a conflict between fibrous and another package that also depends on fibers, but now only fibrous has to guard against itself.

**Comment by willshulman** [comment]
Ah, thanks for the clarification. I did not realize that node-fibers itself had a double-inclusion issue < 1.0.4.

**Comment by willshulman** [comment]
Thanks James!
