### ISSUE TITLE
"Cannot redefine property: future" when using a module that uses fibrous

### ISSUE THREAD

**Issue by demands** [goodeggs/fibrous#37]
My app has a dep tree with two versions of fibrous in it:

```
> npm ls fibrous
customers-api@0.0.2 /Users/maxedmands/Projects/ops-super/apps/customers-api
├── fibrous@0.3.3
└─┬ goodeggs-ops-common@4.0.0
  └── fibrous@0.3.3
```

when I run code that tries to use the inner fibrous, I get this error:

```
[14:19:23] TypeError: Cannot redefine property: future
  at Function.defineProperty (native)
  at defineMemoizedPerInstanceProperty (/Users/maxedmands/Projects/ops-super/apps/customers-api/node_modules/goodeggs-ops-common/node_modules/fibrous/lib/fibrous.js:107:19)
  at Object.<anonymous> (/Users/maxedmands/Projects/ops-super/apps/customers-api/node_modules/goodeggs-ops-common/node_modules/fibrous/lib/fibrous.js:135:5)
  at Object.<anonymous> (/Users/maxedmands/Projects/ops-super/apps/customers-api/node_modules/goodeggs-ops-common/node_modules/fibrous/lib/fibrous.js:189:4)
  at Module._compile (module.js:460:26)
  at Object.Module._extensions..js (module.js:478:10)
  at Module.load (/Users/maxedmands/Projects/ops-super/apps/customers-api/node_
```

Is there any real reason two versions of fibrous can't coexist? Should we just check to see if `Object.(future|sync)` is already defined and avoid trying to do it again?

**Comment by rothfels** [comment]
@demands just ran into the same issue. Subtle and annoying.
